name: DynamicNFTs prod pipe

on:
    push:
        branches:
          - "master"

env:
    ENVIRONMENT: prod
    PROJECT_NAME: dynamic-nfts
    IMAGE_TAG: ${{ github.ref_name }}
    AWS_REGION: eu-west-3

jobs:
    deploy-infra:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref_name }}
                  path: ${{ env.PROJECT_NAME }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.2.2

            - name: Terraform Init
              run: |
                  terraform -chdir=${{ env.PROJECT_NAME }}/.deployment init -backend-config="key=${{ env.PROJECT_NAME }}/prod"

            - name: Terraform apply
              env:
                TF_VAR_project_name: ${{ env.PROJECT_NAME }}
                TF_VAR_environment: ${{ env.ENVIRONMENT }}
                TF_VAR_ipfs_login: ${{ secrets.ADMIN_IPFS_LOGIN }}
                TF_VAR_ipfs_password: ${{ secrets.ADMIN_IPFS_PASSWORD }}
              run: terraform -chdir=${{ env.PROJECT_NAME }}/.deployment apply -var-file="variables.tfvars" -auto-approve

            - name: Recover Terraform outputs
              run: | 
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecr_repository-ipfs-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecr_repository-ipfs-name 
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecr_repository-frontend-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecr_repository-frontend-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecr_repository-backend-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecr_repository-backend-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecs_task_definition-frontend-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecs_task_definition-frontend-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecs_task_definition-ipfs-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecs_task_definition-ipfs-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecs_service-ipfs-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecs_service-ipfs-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecs_service-frontend-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecs_service-frontend-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_ecs_cluster-main-name | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_ecs_cluster-main-name
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_route53_record-frontend | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_route53_record-frontend
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_route53_record-ipfs | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_route53_record-ipfs
                terraform -chdir=${{ env.PROJECT_NAME }}/.deployment output aws_route53_record-ipfs-admin | grep -o '".*"' | sed 's/"//g' | head -n 1 > aws_route53_record-ipfs-admin

            - name: Upload artifact aws_ecr_repository-ipfs-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecr_repository-ipfs-name
                path: aws_ecr_repository-ipfs-name

            - name: Upload artifact aws_ecr_repository-frontend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecr_repository-frontend-name
                path: aws_ecr_repository-frontend-name

            - name: Upload artifact aws_ecr_repository-backend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecr_repository-backend-name
                path: aws_ecr_repository-backend-name

            - name: Upload artifact aws_ecs_task_definition-ipfs-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_task_definition-ipfs-name
                path: aws_ecs_task_definition-ipfs-name

            - name: Upload artifact aws_ecs_task_definition-frontend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_task_definition-frontend-name
                path: aws_ecs_task_definition-frontend-name

            - name: Upload artifact aws_ecs_task_definition-backend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_task_definition-backend-name
                path: aws_ecs_task_definition-backend-name

            - name: Upload artifact aws_ecs_service-ipfs-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_service-ipfs-name
                path: aws_ecs_service-ipfs-name

            - name: Upload artifact aws_ecs_service-frontend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_service-frontend-name
                path: aws_ecs_service-frontend-name

            - name: Upload artifact aws_ecs_service-backend-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_service-backend-name
                path: aws_ecs_service-backend-name

            - name: Upload artifact aws_ecs_cluster-main-name
              uses: actions/upload-artifact@v3
              with:
                name: aws_ecs_cluster-main-name
                path: aws_ecs_cluster-main-name

            - name: Upload artifact aws_route53_record-frontend
              uses: actions/upload-artifact@v3
              with:
                name: aws_route53_record-frontend
                path: aws_route53_record-frontend

            - name: Upload artifact aws_route53_record-backend
              uses: actions/upload-artifact@v3
              with:
                name: aws_route53_record-backend
                path: aws_route53_record-backend                

            - name: Upload artifact aws_route53_record-ipfs
              uses: actions/upload-artifact@v3
              with:
                name: aws_route53_record-ipfs
                path: aws_route53_record-ipfs

            - name: Upload artifact aws_route53_record-ipfs-admin
              uses: actions/upload-artifact@v3
              with:
                name: aws_route53_record-ipfs-admin
                path: aws_route53_record-ipfs-admin                                

    build-backend:
        runs-on: ubuntu-22.04
        needs: deploy-infra

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref_name }}
                  path: ${{ env.PROJECT_NAME }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: aws_ecr_repository-backend-name
                path: /tmp/aws_ecr_repository-backend-name

            - name: Build docker image
              run: |
                cd ${{ env.PROJECT_NAME }}/backend
                docker build -t ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name):${{ env.IMAGE_TAG }} .    

            - name: Tag docker image
              run: |
                docker tag ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name):${{ env.IMAGE_TAG }} ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name):latest

            - name: Push docker image
              run: |
                docker push ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name):${{ env.IMAGE_TAG }}
                docker push ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name):latest
     
              
    deploy-backend:
        runs-on: ubuntu-22.04
        needs: build-backend

        steps:
          - name: Download artifact aws_ecs_task_definition-backend-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_task_definition-backend-name
              path: /tmp/aws_ecs_task_definition-backend-name

          - name: Download artifact aws_ecr_repository-backend-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecr_repository-backend-name
              path: /tmp/aws_ecr_repository-backend-name

          - name: Download artifact aws_ecs_service-backend-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_service-backend-name
              path: /tmp/aws_ecs_service-backend-name

          - name: Download artifact aws_ecs_cluster-main-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_cluster-main-name
              path: /tmp/aws_ecs_cluster-main-name

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1-node16
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1              

          - name: Download task definition
            id: download-task-definition
            run: |
              aws ecs describe-task-definition --task-definition $(cat /tmp/aws_ecs_task_definition-backend-name/aws_ecs_task_definition-backend-name) --query taskDefinition > task-definition.json
              

          - name: Fill GITHUB_OUTPUT
            id: artifacts
            run: |
              echo "aws_ecs_cluster-main-name=$(cat /tmp/aws_ecs_cluster-main-name/aws_ecs_cluster-main-name)" >> $GITHUB_OUTPUT
              echo "aws_ecs_service-backend-name=$(cat /tmp/aws_ecs_service-backend-name/aws_ecs_service-backend-name)" >> $GITHUB_OUTPUT
              echo "aws_ecr_repository-backend-name=$(cat /tmp/aws_ecr_repository-backend-name/aws_ecr_repository-backend-name)" >> $GITHUB_OUTPUT
              echo "aws_ecs_task_definition-backend-name=$(cat /tmp/aws_ecs_task_definition-backend-name/aws_ecs_task_definition-backend-name)" >> $GITHUB_OUTPUT

          - name: Replace image tag in task definition
            id: fillin-task-definition
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
              task-definition: task-definition.json
              container-name: ${{ steps.artifacts.outputs.aws_ecs_task_definition-backend-name }}
              image: ${{ steps.login-ecr.outputs.registry }}/${{ steps.artifacts.outputs.aws_ecr_repository-backend-name }}:${{ env.IMAGE_TAG }}

          - name: Deploying task definition
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
              task-definition: ${{ steps.fillin-task-definition.outputs.task-definition }}
              service: ${{ steps.artifacts.outputs.aws_ecs_service-backend-name }}
              cluster: ${{ steps.artifacts.outputs.aws_ecs_cluster-main-name }}
              wait-for-service-stability: true

    build-ipfs:
        runs-on: ubuntu-22.04
        needs: deploy-infra

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref_name }}
                  path: ${{ env.PROJECT_NAME }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: aws_ecr_repository-ipfs-name
                path: /tmp/aws_ecr_repository-ipfs-name

            - name: Build docker image
              run: |
                cd ${{ env.PROJECT_NAME }}/ipfs
                docker build -t ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name):${{ env.IMAGE_TAG }} .    

            - name: Tag docker image
              run: |
                docker tag ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name):${{ env.IMAGE_TAG }} ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name):latest

            - name: Push docker image
              run: |
                docker push ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name):${{ env.IMAGE_TAG }}
                docker push ${{ steps.login-ecr.outputs.registry }}/$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name):latest
              
    deploy-ipfs:
        runs-on: ubuntu-22.04
        needs: build-ipfs

        steps:
          - name: Download artifact aws_ecs_task_definition-ipfs-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_task_definition-ipfs-name
              path: /tmp/aws_ecs_task_definition-ipfs-name

          - name: Download artifact aws_ecr_repository-ipfs-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecr_repository-ipfs-name
              path: /tmp/aws_ecr_repository-ipfs-name

          - name: Download artifact aws_ecs_service-ipfs-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_service-ipfs-name
              path: /tmp/aws_ecs_service-ipfs-name

          - name: Download artifact aws_ecs_cluster-main-name
            uses: actions/download-artifact@v3
            with:
              name: aws_ecs_cluster-main-name
              path: /tmp/aws_ecs_cluster-main-name

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1-node16
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1              

          - name: Download task definition
            id: download-task-definition
            run: |
              aws ecs describe-task-definition --task-definition $(cat /tmp/aws_ecs_task_definition-ipfs-name/aws_ecs_task_definition-ipfs-name) --query taskDefinition > task-definition.json
              

          - name: Fill GITHUB_OUTPUT
            id: artifacts
            run: |
              echo "aws_ecs_cluster-main-name=$(cat /tmp/aws_ecs_cluster-main-name/aws_ecs_cluster-main-name)" >> $GITHUB_OUTPUT
              echo "aws_ecs_service-ipfs-name=$(cat /tmp/aws_ecs_service-ipfs-name/aws_ecs_service-ipfs-name)" >> $GITHUB_OUTPUT
              echo "aws_ecr_repository-ipfs-name=$(cat /tmp/aws_ecr_repository-ipfs-name/aws_ecr_repository-ipfs-name)" >> $GITHUB_OUTPUT
              echo "aws_ecs_task_definition-ipfs-name=$(cat /tmp/aws_ecs_task_definition-ipfs-name/aws_ecs_task_definition-ipfs-name)" >> $GITHUB_OUTPUT

          - name: Replace image tag in task definition
            id: fillin-task-definition
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
              task-definition: task-definition.json
              container-name: ${{ steps.artifacts.outputs.aws_ecs_task_definition-ipfs-name }}
              image: ${{ steps.login-ecr.outputs.registry }}/${{ steps.artifacts.outputs.aws_ecr_repository-ipfs-name }}:${{ env.IMAGE_TAG }}

          - name: Deploying task definition
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
              task-definition: ${{ steps.fillin-task-definition.outputs.task-definition }}
              service: ${{ steps.artifacts.outputs.aws_ecs_service-ipfs-name }}
              cluster: ${{ steps.artifacts.outputs.aws_ecs_cluster-main-name }}
              wait-for-service-stability: true

    generate-and-upload-nfts-to-ipfs:
        runs-on: ubuntu-22.04
        needs: deploy-ipfs

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
                ref: ${{ github.ref_name }}
                path: ${{ env.PROJECT_NAME }}

          - name: Download artifact aws_route53_record-ipfs-admin
            uses: actions/download-artifact@v3
            with:
              name: aws_route53_record-ipfs-admin
              path: /tmp/aws_route53_record-ipfs-admin

          - name: Fill GITHUB_OUTPUT
            id: artifacts
            run: |
              echo "aws_route53_record-ipfs-admin=$(cat /tmp/aws_route53_record-ipfs-admin/aws_route53_record-ipfs-admin)" >> $GITHUB_OUTPUT

          - name: Install npm packages and execute uploadNftsToIpfs yarn script
            env:
                IPFS_LOGIN: ${{ secrets.ADMIN_IPFS_LOGIN }}
                IPFS_PASSWORD: ${{ secrets.ADMIN_IPFS_PASSWORD }}
                IPFS_ADMIN_HOST: ${{ steps.artifacts.outputs.aws_route53_record-ipfs-admin }}
            run: |
              cd ${{ env.PROJECT_NAME }}
              yarn
              yarn uploadNftsToIpfs

          - name: Upload artifact generated_nft_cids
            uses: actions/upload-artifact@v3
            with:
              name: generated_nft_cids
              path: ${{ env.PROJECT_NAME }}/nftdata/generated

    install-run-foundry:
        runs-on: ubuntu-22.04
        needs: generate-and-upload-nfts-to-ipfs

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
                ref: ${{ github.ref_name }}
                path: ${{ env.PROJECT_NAME }}

          - name: Install Foundry
            uses: foundry-rs/foundry-toolchain@v1
            with:
              version: nightly